### PR TITLE
Allow Custom Date formatting when dumping

### LINKED ISSUE #88: Allow Date formatting when dumping
I'd like to be able to dump a Date object in a desired format, personally YYYY-MM-DD with no time stamp.

I thought I could use the objectEncoder, but there appears to be an exception for Date objects https://github.com/jeremyfa/yaml.js/blob/develop/lib/Inline.js#L97

If there was no exception made for Date objects, this would become possible and we'd be able to use any date formatting library without adding a dependency to yaml.js

e.g.

```javascript
    type = typeof value;
    if (type === 'object') {
      if (objectEncoder != null) {
        result = objectEncoder(value);
        if (typeof result === 'string' || (result != null)) {
          return result;
        }
      }
      if (value instanceof Date) {
        return value.toISOString();
      }
      return this.dumpObject(value);
    }
```

### PR DESCRIPTION
**Pull request by zachwhaley**
This allows for customizing date formats when dumping

Fixes #88

### CODE REVIEW

**Comment by jeremyfa** [comment]
Thanks for the PR!

However I don't think I can merge it as is. If I did, it would break any code that does provide an objectEncoder but doesn't (want to?) take care of date formatting.

I'd rather let the user provide an optional "dateEncoder" function (similar to objectEncoder), so that it doesn't break current behavior, and allows to fully customize date formatting independently. I guess we would also need to ensure the formatted date will be decoded properly (by adding a "dateDecoder" option).

If you can change the PR to fit with these requirements, I will merge it 👍

**Comment by zachwhaley** [comment]
Cool ☺️
Will do!

**Comment by zachwhaley** [comment]
Looking at this some more, I'm wondering if it would be more appropriate to instead expand on the Date parsing and dumping code to detect the format being used in the yaml, and stick to that, or at least distinguish between date formats (2017-06-02) and time formats (2017-06-02T16:26:24.1Z)

It would definitely be easier to just add the date encoder/decoder, but then people would be allowed to add non-standard formats to their yaml.

What do you think?

**Comment by jeremyfa** [comment]
_Sorry for late reply,_

I believe we can't assume whether a date was a date (without hours/min/seconds) or a datetime when dumping to Yaml. The solution of providing a custom dateEncoder would allow to have control on this when needed with your own domain-specific logic, but I don't think yaml.js itself should assume what format to dump to. It should just use default (full datetime), unless a custom dateEncoder is provided.

**Comment by zachwhaley** [comment]
Okay.

I doubt I'll work on this anytime soon, so please don't wait on me if you feel the desire to finish it.

**Comment by jeremyfa** [comment]
Closing it for now, feel free to reopen this if you end up completing it.

**Pull request closed without merging**
