### PR TITLE
Replaced reserved javascript keyword "char" with "_char"

### PR DESCRIPTION
**Pull request by phpdave11**
Fixes Adobe ExtendScript compile error.

### CODE REVIEW

**Comment by phpdave11** [comment]
Hey jeremyfa, great YAML library! One nit: I ran into an issue where the JavaScript engine that I am using this for (Adobe ExtendScript) complained that "char" was a reserved keyword. I've submitted a pull request that fixes this issue.

**Comment by jeremyfa** [comment]
Is this still an issue with Adobe ExtendScript?

**Comment by phpdave11** [comment]
Yes.  And "char" is a future reserved word, so it should not be used.  http://stackoverflow.com/a/147776

**Comment by jeremyfa** [comment]
Thanks!

**Pull request merged**
